
server:
  port: 8080

spring:
  application:
    name: BloodPressure

# Application Insights Instrumentation Key
azure:
  application-insights:
    instrumentation-key: e1d805b6-8e24-4cbc-8a14-79dad611fc9d

logging:
  level:
    root: info
