
server:
  port: 8080

spring:
  application:
    name: BloodPressure

# Application Insights Instrumentation Key
azure:
  application-insights:
    instrumentation-key: cf8bce09-34ce-4777-8322-c7ca0034bce1

logging:
  level:
    root: info
