name: k6 Performance Test

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  k6:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Build API
        run: mvn clean install -DskipTests

      - name: Start Bloodpressure App
        run: |
          nohup java -jar target/*.jar &
          sleep 15

      - name: Set up k6
        uses: grafana/setup-k6-action@v1

      - name: Run k6 performance test
        uses: grafana/run-k6-action@v1
        with:
          path: |
            k6/post-test.js
          flags: --out json=results.json

      - name: Upload k6 results
        uses: actions/upload-artifact@v4
        with:
          name: k6-results
          path: results.json