# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - bp-test-java-app

on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize, reopened ]
  workflow_dispatch:

jobs:

  vulnerability-check:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Set up JDK 17
          uses: actions/setup-java@v4
          with:
            distribution: temurin
            java-version: 17

        - name: Cache Maven
          uses: actions/cache@v4
          with:
            path: ~/.m2/repository
            key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
            restore-keys: |
              ${{ runner.os }}-m2-

        - name: Run SpotBugs (with FindSecBugs)
          run: mvn -q clean verify -DskipTests=false

        - name: Upload vulnerability report
          uses: actions/upload-artifact@v4
          with:
            name: spotbug-report
            path: |
              target/spotbugsXml.xml
              target/site/spotbugs.html

        - name: Generate JaCoCo Coverage Report
          run: mvn jacoco:report

        - name: Upload JaCoCo coverage
          uses: actions/upload-artifact@v4
          with:
            name: jacoco-report
            path: |
              target/site/jacoco/jacoco.xml
              target/site/jacoco/
            if-no-files-found: ignore

        - name: Cache SonarQube packages
          uses: actions/cache@v4
          with:
            path: ~/.sonar/cache
            key: ${{ runner.os }}-sonar
            restore-keys: ${{ runner.os }}-sonar

#        - name: Run SonarQube Code coverage
#          run: mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Pcoverage

#        - name: SonarCloud Scan
#          uses: sonarsource/sonarcloud-github-action@v2
#          env:
#            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#            SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
#          with:
#            args: >
#              -Dsonar.projectKey=adithyan-ie_blood-pressure-ca1
#              -Dsonar.organization=adithyan-ie
#              -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml


        - name: SonarQube Scan
          env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        #  run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=adithyan-ie_blood-pressure-ca1
          run: mvn sonar:sonar \
            -Dsonar.projectKey=adithyan-ie_blood-pressure-ca1 \
            -Dsonar.projectName="Blood Pressure" \
            -Dsonar.sources=src/main/java \
            -Dsonar.java.binaries=target/classes \
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}


  run_tests:
    needs : vulnerability-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up java version
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'microsoft'

      - name: Run Test
        run: mvn clean test

      - name: Upload JUnit Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: junit-reports
          path: target/surefire-reports/*.xml
          if-no-files-found: ignore



  build:
    needs: run_tests
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'microsoft'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

#  deploy:
#    runs-on: windows-latest
#    needs: build
#
#
#    steps:
#      - name: Download artifact from build job
#        uses: actions/download-artifact@v4
#        with:
#          name: java-app
#
#      - name: Deploy to Azure Web App
#        id: deploy-to-webapp
#        uses: azure/webapps-deploy@v3
#        with:
#          app-name: 'bp-test-java-app'
#          slot-name: 'Production'
#          package: '*.jar'
#          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_9C76509E88C34E8EB1B370CE0EC75F6A }}