name: Perform necessary security tests
on:
  push:
    branches: [ qa ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  security-testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          - ref: development

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      - name: Build API
        run: mvn clean package -DskipTests

      - name: Start Bloodpressure App
        run: |
          nohup java -jar target/*.jar &
          echo "Waiting for app to be ready..."
          for i in {1..30}; do
            if nc -z localhost 8080; then
              echo "App is up!"
              break
            fi
            sleep 2
          done

      - name: Set up k6
        uses: grafana/setup-k6-action@v1

      - name: Run k6 performance test
        uses: grafana/run-k6-action@v1
        with:
          path: |
            k6/post-test.js
          flags: --out json=results.json

      - name: Upload k6 Performance results
        uses: actions/upload-artifact@v4
        with:
          name: k6-results
          path: |
            results.json

      - name: Run Penetration Test using OWASP ZAP
        uses: zaproxy/action-baseline@v0.15.0
        with:
          target: "http://localhost:8080" # base URL
          docker_name: "ghcr.io/zaproxy/zaproxy:stable"
          cmd_options: >
            -r zap-report.html
            -t 120
            z "msg=/bp,method=POST,body={\"systolic\":120,\"diastolic\":80},headers={\"Content-Type\":\"application/json\"}"